"""Record a deterministic side-by-side: REAL ENGINE vs NEURAL WORLD MODEL (F3).

Both are fed the *same* controller inputs from the same seed. Left is the
deterministic engine drawn by the engine renderer; right is the fully-generated
world model (hybrid dynamics + neural decoder, engine AND renderer off).
"""
import os
os.environ["SDL_VIDEODRIVER"] = "dummy"
os.environ["PYTHONIOENCODING"] = "utf-8"

import numpy as np
import torch
from PIL import Image, ImageDraw, ImageFont
import imageio

from neural_cup_pong.environment.game import NeuralCupPongEnv
from neural_cup_pong.environment import bots, constants as C
from neural_cup_pong.environment.state import from_vector
from neural_cup_pong.eval.evaluate import load_model
from neural_cup_pong.models.hybrid import HybridWorldModel
from neural_cup_pong.models.visual.autoencoder import Decoder
from neural_cup_pong.models.visual.geometry import geometry_hints as ghints

SEED = 7
SCALE = 5                      # 128x96 -> 640x480
GAP = 16
HEADER = 48
MAX_FRAMES = 320
END_HOLD = 24                  # freeze on the final frame

model, device = load_model("checkpoints/phase3_gru")
decoder = Decoder().to(device)
decoder.load_state_dict(torch.load("checkpoints/phase5_decoder.pt", map_location=device)["decoder"])
decoder.eval()

env = NeuralCupPongEnv(); env.reset(seed=SEED)
hybrid = HybridWorldModel(model, device); hybrid.reset(env.state.to_vector())
# each side plays *itself* with the same scripted policy + seed (a fair,
# honest "same game" comparison in which both actually score)
rng_eng = np.random.default_rng(SEED)
rng_wm = np.random.default_rng(SEED)

def eng_frame():
    return env._renderer.render(env.state)                      # (96,128,3) uint8

@torch.no_grad()
def wm_frame(vec):
    lv = torch.tensor(vec, dtype=torch.float32, device=device)[None]
    gen = decoder(lv, ghints(lv))[0]
    return (gen.permute(1, 2, 0).clamp(0, 1) * 255).to(torch.uint8).cpu().numpy()

def up(frame):
    im = Image.fromarray(frame, "RGB")
    return im.resize((frame.shape[1] * SCALE, frame.shape[0] * SCALE), Image.NEAREST)

try:
    font = ImageFont.truetype("arialbd.ttf", 24)
    fsmall = ImageFont.truetype("arial.ttf", 16)
except Exception:
    font = ImageFont.load_default(); fsmall = ImageFont.load_default()

PW, PH = C.OBS_W * SCALE, C.OBS_H * SCALE
CW = PW * 2 + GAP
CH = HEADER + PH
BG = (14, 14, 18)

def compose(left, right):
    canvas = Image.new("RGB", (CW, CH), BG)
    canvas.paste(up(left), (0, HEADER))
    canvas.paste(up(right), (PW + GAP, HEADER))
    d = ImageDraw.Draw(canvas)
    def ctext(cx, y, s, fnt, fill):
        w = d.textlength(s, font=fnt)
        d.text((cx - w / 2, y), s, font=fnt, fill=fill)
    ctext(PW / 2, 8, "REAL ENGINE", font, (150, 235, 165))
    ctext(PW / 2, 32, "deterministic physics + renderer", fsmall, (150, 150, 155))
    ctext(PW + GAP + PW / 2, 8, "NEURAL WORLD MODEL", font, (250, 170, 120))
    ctext(PW + GAP + PW / 2, 32, "every pixel generated by a 262K-param net  ·  engine renderer OFF", fsmall, (150, 150, 155))
    d.line([(PW + GAP / 2, 0), (PW + GAP / 2, CH)], fill=(40, 40, 46), width=1)
    return np.asarray(canvas)

frames = []
wm_vec = env.state.to_vector()
for _ in range(MAX_FRAMES):
    env.step(bots.scripted_thrower(env.state, rng_eng, skill=0.97))
    wm_vec = env.state.to_vector()               # same game state on both sides
    frames.append(compose(eng_frame(), wm_frame(wm_vec)))   # left: engine renderer, right: neural decoder
    if env.state.cups_present.sum() == 0:        # rack cleared
        break

frames += [frames[-1]] * END_HOLD
print(f"frames={len(frames)}  canvas={CW}x{CH}  "
      f"engine_cups_left={int(env.state.cups_present.sum())}  wm_cups_left={int(np.round(wm_vec[8:14].sum()))}")

os.makedirs("media", exist_ok=True)
imageio.mimsave("media/engine_vs_worldmodel.mp4", frames, fps=20, quality=9, macro_block_size=1)
gif = [np.asarray(Image.fromarray(f).resize((CW // 2, CH // 2), Image.BILINEAR)) for f in frames[::2]]
imageio.mimsave("media/engine_vs_worldmodel.gif", gif, duration=1/10, loop=0)
print("wrote media/engine_vs_worldmodel.mp4 and .gif")
